### ISSUE TITLE
Can't get author and color

### ISSUE THREAD

**Issue by akiki19950827** [thiswillbeyourgithub/LogseqPDFImporter#1]
![屏幕截图 2023-09-21 160048](https://github.com/thiswillbeyourgithub/pdfannotations_to_logseq/assets/7312175/e06afc89-fed4-4dfd-88f4-bfc533dc3d84)
When I used the program to extract comments, the bottom sentence in the image was extracted first, and then the top part. And in the top part I extract, I expect it to extract all of it, but it only extracts "bit [3:0][2:1] B" and ends. So I changed the variable "_threshold_intersection" to 0.3 and it worked. The next problem is lines 211 and 215, which indicate that there are no "t" and "c" keys. After debugging I found that the new object in line 284 does not have these two properties.

**Comment by thiswillbeyourgithub** [comment]
Hi!

Yeah the _threshold_intersection is annoying.

Regarding this t/c thing. I don't understand something. Where is the author stored if not in a "t" key ? Same question for color

**Comment by akiki19950827** [comment]
First of all, thank you for your reply.
I uploaded two pictures to illustrate this problem.
![图片1](https://github.com/thiswillbeyourgithub/pdfannotations_to_logseq/assets/7312175/53ff101e-0d60-44cc-aa1b-1ca4b4c97598)
In the green box of the first image is the second note. Obviously the corresponding annot dict has no 't' or 'c' key.
![图片2](https://github.com/thiswillbeyourgithub/pdfannotations_to_logseq/assets/7312175/629111ef-5930-402b-b568-c7182824b9c7)
In the second image, it appears that the second comment has many fewer attributes than the first, and the subtype is considered popup instead of highlight.
I also added the pdf of this page as an attachment, hoping to facilitate your debugging.
[test.pdf](https://github.com/thiswillbeyourgithub/pdfannotations_to_logseq/files/12695757/test.pdf)

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot for making it easy for me.

I pushed a few commits. I made it not crash if "t" or "c" is missing, added a docstring, made the default author to unknown, made the threshold an input argument, and a few other errands.

I'll close this for now but don't hesitate to reopen or open an other one if I missed something.

Have a nice day.

**Comment by thiswillbeyourgithub** [comment]
Btw @akiki19950827  this project contained numerous imperfections and is now far better. Notably the anotation location should be fine now.
