### ISSUE TITLE
Unknown commands and dependencies plus a fitz.open error

### ISSUE THREAD

**Issue by mthibode13** [thiswillbeyourgithub/LogseqPDFImporter#2]
Hi-- thanks for your work here to extend fannots. 

In my case, I just want to pull in a bunch of pdfs and their annotations into logseq. The issues I've had are that I needed in install the following modules: fitz; frontend; fire; simplejson; colormath; and tools. 

O.K. got that done, but still experienced this error output. 
...__init__.py", line 291, in main
    readerfitz = fitz.open(input_path)  # separate reader that handles annotation text better
AttributeError: module 'fitz' has no attribute 'open'

I am not a programmer, so I can't come up with a PR, but was wondering whether you had similar issues that might be obvious for you to fix. I might try to do a PR on the readme file and add the modules that one should have installed, e.g., colormath etc.

Thanks

**Comment by thiswillbeyourgithub** [comment]
Thanks for reaching out. We'll sort this out!
Whare system are you on? Mac, linux etc
What version of fitz do you have? (pip freeze | grep fitz)

**Comment by mthibode13** [comment]
fitz==0.0.1.dev2
macOS Sonoma 14.2

**Comment by thiswillbeyourgithub** [comment]
I just uploaded a requirements.txt file.

fitz is actually not the right package, it's pymupdf for reasons

**Comment by thiswillbeyourgithub** [comment]
Btw @mthibode13  this project contained numerous imperfections and is now far better. Notably the anotation location should be fine now.
